include: package:pedantic/analysis_options.yaml
analyzer:
  strong-mode:
    implicit-casts: false
linter:
  rules:
    # Errors
    - avoid_empty_else
    - await_only_futures
    - comment_references
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - test_types_in_equals
    - throw_in_finally
    - unawaited_futures
    - unrelated_type_equality_checks
    - valid_regexps

    # Style
    - annotate_overrides
    - avoid_init_to_null
    - avoid_return_types_on_setters
    - camel_case_types
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - prefer_final_fields
    - prefer_generic_function_type_aliases
    - prefer_is_not_empty
    - prefer_typing_uninitialized_variables
    - slash_for_doc_comments
    - type_init_formals
    - unnecessary_const
    - unnecessary_new
